spring.application.name=lab6
spring.datasource.url=jdbc:postgresql://localhost:5432/lab6_java
spring.datasource.username=nikita
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update